### ISSUE TITLE
SSL Connect error

### ISSUE THREAD

**Issue by djs070** [messagemedia/messagemedia-soap-api-ruby-sdk#11]
Hi guys

Getting the following error when trying to send:

```
E, [2016-02-29T16:21:36.122116 #2188] ERROR -- : SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

E, [2016-02-29T16:21:36.122116 #2188] ERROR -- : ["C:/Ruby21/lib/ruby/gems/2.1.0/gems/httpi-2.4.1/lib/httpi/adapter/net_http.rb:46:in `rescue in request'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/httpi-2.4.1/lib/httpi/adapter/net_http.rb:30:in `request'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/httpi-2.4.1/lib/httpi.rb:162:in `request'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/httpi-2.4.1/lib/httpi.rb:127:in `get'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/wasabi-3.5.0/lib/wasabi/resolver.rb: 43:in `load_from_remote'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/wasabi-3.5.0/lib/ wasabi/resolver.rb:33:in `resolve'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/wasabi-3.5.0/lib/wasabi/document.rb:142:in `xml'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/ wasabi-3.5.0/lib/wasabi/document.rb:160:in `parse'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/wasabi-3.5.0/lib/wasabi/document.rb:147:in `parser'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/wasabi-3.5.0/lib/wasabi/document.rb:64:in `soap_actions'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/savon-2.11.1/lib/savon/operation.rb:22:in `ensure_exists!'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/savon-2.11.1/lib/savon/operation.rb:15:in `create'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/savon-2.11.1/lib/savon/client.rb:32:in `operation'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/savon-2.11.1/lib/savon/client.rb:36:in `call'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/messagemedia-ruby-0.7.1/lib/messagemedia/soap/client.rb:107:in `send_messages'", "C:/Projects/bernice/lib/bernice/message_service.rb:35:in `send_messages'", "C:/Projects/bernice/lib/bernice/message_service.rb:18:in `block in build_and_send_messages'", "C:/Projects/bernice/lib/bernice/message_service.rb:15:in `each'", "C:/Projects/bernice/lib/bernice/message_service.rb:15:in `collect'", "C:/Projects/bernice/lib/bernice/message_service.rb:15:in `build_and_send_messages'", "C:/Projects/bernice/lib/bernice.rb:30:in `run'", "bin/bernice:21:in `<main>'"]
```

Is there anything that's changed that would cause this to happen? I've run successfully some time ago and was just about to go to production when this popped up.

Thanks

**Comment by pcolby** [comment]
Hi @precise54,

> Is there anything that's changed that would cause this to happen?

Not that I'm aware of.  Can you have a look at the certificate details as viewed by your machine? Since you appear to be using Windows, the easiest way is probably to use your browser (IE, FF, or Chrome) to visit https://soap.m4u.com.au/ then click on the little (green or red) padlock next to the address.  That will at least tell us if its Ruby-specific problem, or system-wide CA chain issue.

Cheers.

**Comment by precise54** [comment]
Hi @pcolby, thanks for getting back to me

All appears to be fine from the browser - I think I've discovered it's actually not specific to the messagemedia domain so I'll do some more investigating on my side.
